### PR TITLE
Caching in Redis

### LINKED ISSUE #7: Disable timeout / cache results
Computation can take a lot of time, so it isn't interrupted.

Moreover, result stays same for the same input, so we could cache tuple (task, input, ouput) in Redis, so a refreshed request is responded to immediately.

### PR DESCRIPTION
**Pull request by garncarz**
Closes #7.

### CODE REVIEW

**Comment by garncarz** [comment]
This should be helpful in case Nginx request is interrupted (e.g. timeouted), then a Celery worker finishes computation and saves the result in Redis. The next time the same request arrives, the cached result is used immediately.

But on the other hand, it can break things, e.g. if all requests to the cache would return the same result. So please review. It would be also cool to have some testing mechanism, which would test against a real server (so not CI), e.g. by calling HTTPie.

**Review by dzejar — APPROVED** [review]
ok

**Comment by pholasek** [comment]
this is not bad

**Comment by garncarz** [comment]
This pull request was very poorly reviewed, I had to fix it by 134c3f577e5ab4d503baa0b34b1368de77fd5e93 and 92b70dead765e4cd7b1d5c5334d5eade9d4175cb.

**Pull request merged**
