### PR TITLE
Task 1 solver bound

### PR DESCRIPTION
**Pull request by garncarz**

### CODE REVIEW

**Comment by garncarz** [comment]
@pholasek Please fix this on Travis.

**Comment by garncarz** [comment]
@pholasek Won't https://jsteemann.github.io/blog/2014/10/17/using-travis-ci-for-a-c-plus-plus-11-project/ help?

**Comment by pholasek** [comment]
Ok, it builds now, the next problem is 
```
g++-6 -Wall find_hub.o -o find_hub

0.00s$ ./test.sh

/home/travis/build.sh: line 62: ./test.sh: No such file or directory
```

**Comment by garncarz** [comment]
Oh, just `cd` back, or preferably `pushd`, `popd`.

**Comment by pholasek** [comment]
Ok, seems ok, feel free to merge to master or continue here if binding not completed.

**Pull request merged**
